### ISSUE TITLE
Dead link to TorusWeights.csv

### ISSUE THREAD

**Issue by joaodinissf** [damaggu/grid_cell_exercise_public#1]
The [link provided](http://www.goo.gl/TE8A0d) in the Python Notebook to download the file "TorusWeights.csv" does not appear to be working.

**Comment by joaodinissf** [comment]
I have figured out the problem - while http://www.goo.gl/TE8A0d leads to a 404 page, http://goo.gl/TE8A0d appears to link to the intended destination.

**Comment by damaggu** [comment]
fixed it, thanks a lot @Amazong
